[package]
name = "blockchain_project"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "2.0.1"
blake3 = "1.8.1"
rs_merkle = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
